USE DATABASE WALMART_DEV;
USE SCHEMA WALETP;

TRUNCATE TABLE WALETP.CALENDAR_DIM;

INSERT INTO WALETP.CALENDAR_DIM
(
	CAL_DT,
    CAL_TYPE_NAME,
    DAY_OF_WK_NUM,
    YR_NUM,
    WK_NUM,
    YR_WK_NUM,
    MNTH_NUM,
    YR_MNTH_NUM,
    QTR_NUM,
    YR_QTR_NUM
)
SELECT
	CAL_DT AS CAL_DT,
	CAL_TYPE_DESC AS CAL_TYPE_NAME,
	DAY_OF_WK_NUM AS DAY_OF_WK_NUM,
	YR_NUM AS YR_NUM,
	WK_NUM AS WK_NUM,
	YR_WK_NUM  AS YR_WK_NUM,
	MNTH_NUM AS MNTH_NUM,
	YR_MNTH_NUM  AS YR_MNTH_NUM,
	QTR_NUM AS QTR_NUM,
	YR_QTR_NUM AS YR_QTR_NUM
FROM WALLND.CALENDAR
;


SELECT * FROM WALETP.CALENDAR_DIM LIMIT 10;