USE DATABASE WALMART_DEV;
USE SCHEMA WALETP;

TRUNCATE TABLE WALETP.PRODUCT_DIM;

INSERT INTO WALETP.PRODUCT_DIM 
(
	PROD_KEY,
	PROD_NAME,
	VOL,
	WGT,
	BRAND_NAME,
	STATUS_CODE,
	STATUS_CODE_NAME,
	CATEGORY_KEY,
	CATEGORY_NAME,
	SUBCATEGORY_KEY,
	SUBCATEGORY_NAME,
	TLOG_ACTIVE_FLG,
	START_DATE,
	END_DATE
)
SELECT
	PROD_KEY AS PROD_KEY,
	PROD_NAME AS PROD_NAME,
	VOL AS VOL,
	WGT AS WGT,
	BRAND_NAME AS BRAND_NAME,
	STATUS_CODE AS STATUS_CODE,
	STATUS_CODE_NAME AS STATUS_CODE_NAME,
	CATEGORY_KEY AS CATEGORY_KEY,
	CATEGORY_NAME AS CATEGORY_NAME,
	SUBCATEGORY_KEY AS SUBCATEGORY_KEY,
	SUBCATEGORY_NAME SUBCATEGORY_NAME,
	TRUE AS TLOG_ACTIVE_FLG,
	NULL AS START_DATE,
	NULL AS END_DATE
FROM WALLND.PRODUCT
;

SELECT * FROM WALETP.PRODUCT_DIM;
	