USE DATABASE WALMART_DEV;
USE SCHEMA WALETP;

TRUNCATE WALETP.DAILY_SALES;

SET LAST_DATE = (SELECT MAX(CAL_DT) FROM WALETP.DAILY_SALES);
SELECT $LAST_DATE;

DELETE FROM WALETP.DAILY_SALES WHERE CAL_DT=$LAST_DATE;
SELECT MAX(CAL_DT) FROM WALETP.DAILY_SALES;

INSERT INTO WALETP.DAILY_SALES
(
	CAL_DT,
   	PROD_KEY,
   	STORE_KEY,
   	SALES_QTY,
   	SALES_PRICE,
   	SALES_AMT,
   	DISCOUNT,
   	SALES_COST,
   	SALES_MARGIN,
   	SHIP_COST
)
SELECT
	TRANS_DT AS CAL_DT,
   	PROD_KEY AS PROD_KEY,
   	STORE_KEY AS STORE_KEY,
   	SUM(SALES_QTY) AS SALES_QTY,
   	AVG(SALES_PRICE) AS SALES_PRICE,
   	SUM(SALES_AMT) AS SALES_AMT,
   	AVG(DISCOUNT) AS DISCOUNT,
   	SUM(SALES_COST) AS SALES_COST,
   	SUM(SALES_MARGIN) AS SALES_MARGIN,
   	SUM(SHIP_COST) AS SHIP_COST
FROM WALLND.SALES
WHERE CAL_DT>=NVL($LAST_DATE, '1900-01-01')
GROUP BY 1,2,3
ORDER BY 1,2,3
;

