USE DATABASE WALMART_DEV;

TRUNCATE TABLE WALSUP.SALES_INV_STORE_DAY;

INSERT INTO WALSUP.SALES_INV_STORE_DAY
(
	CAL_DT,
	STORE_KEY,
	PROD_KEY,
	SALES_QTY,
	SALES_PRICE,
	SALES_AMT,
	DISCOUNT,
	SALES_COST,
	SALES_MARGIN,
	STOCK_ON_HAND_QTY,
	ORDERED_STOCK_QTY,
	OUT_OF_STOCK_FLG,
	IN_STOCK_FLG,
	LOW_STOCK_FLG
)
SELECT
	S.CAL_DT,
	S.STORE_KEY,
	S.PROD_KEY,
	S.SALES_QTY,
	S.SALES_PRICE,
	S.SALES_AMT,
	S.DISCOUNT,
	S.SALES_COST,
	S.SALES_MARGIN,
	I.STOCK_ON_HAND_QTY,
	I.ORDERED_STOCK,
	I.OUT_OF_STOCK_FLG,
	CASE 
		WHEN I.OUT_OF_STOCK_FLG=TRUE THEN FALSE 
	ELSE TRUE 
	END AS IN_STOCK_FLG,
	CASE 
		WHEN I.STOCK_ON_HAND_QTY<S.SALES_QTY THEN TRUE
	ELSE FALSE
	END AS LOW_STOCK_FLG
FROM WALETP.DAILY_SALES AS S
FULL OUTER JOIN WALETP.INVENTORY AS I 
USING (CAL_DT, STORE_KEY, PROD_KEY)
;
	