USE DATABASE WALMART_DEV;
USE SCHEMA WALSUP;

CREATE OR REPLACE TABLE WALSUP.CALENDAR_DIM CLONE WALETP.CALENDAR_DIM;

CREATE OR REPLACE TABLE WALSUP.STORE_DIM CLONE WALETP.STORE_DIM;

CREATE OR REPLACE TABLE WALSUP.PRODUCT_DIM CLONE WALETP.PRODUCT_DIM;

TRUNCATE IF EXISTS WALSUP.SALES_INV_STORE_DAY;
CREATE OR REPLACE TABLE WALSUP.SALES_INV_STORE_DAY
(
	CAL_DT DATE,
	STORE_KEY INTEGER,
	PROD_KEY INTEGER,
	SALES_QTY NUMBER(38,2),
	SALES_PRICE NUMBER(38,2),
	SALES_AMT NUMBER(38,2),
	DISCOUNT NUMBER(38,2),
	SALES_COST NUMBER(38,2),
	SALES_MARGIN NUMBER(38,2),
	STOCK_ON_HAND_QTY NUMBER(38,2),
	ORDERED_STOCK_QTY NUMBER(38,2),
	OUT_OF_STOCK_FLG BOOLEAN,
	IN_STOCK_FLG BOOLEAN,
	LOW_STOCK_FLG BOOLEAN,
	UPDATE_TIME TIMESTAMP
);

TRUNCATE IF EXISTS WALSUP.SALES_INV_STORE_WKLY;
CREATE OR REPLACE TABLE WALSUP.SALES_INV_STORE_WKLY
(
	YR_NUM INTEGER,
	WK_NUM INTEGER,
	STORE_KEY INTEGER,
	PROD_KEY INTEGER,
	WK_SALES_QTY NUMBER(38,2),
	AVG_SALES_PRICE NUMBER(38,2),
	WK_SALES_AMT NUMBER(38,2),
	WK_DISCOUNT NUMBER(38,2),
	WK_SALES_COST NUMBER(38,2),
	WK_SALES_MARGIN NUMBER(38,2),
	EOP_STOCK_ON_HAND_QTY NUMBER(38,2),
	EOP_ORDERED_STOCK_QTY NUMBER(38,2),
	OUT_OF_STOCK_TIMES INTEGER,
	IN_STOCK_TIMES INTEGER,
	LOW_STOCK_TIMES INTEGER,
	POTENTIAL_LOW_STOCK_IMPACT INTEGER,
	UPDATE_TIME TIMESTAMP
);