USE SCHEMA WALETP;


CREATE OR REPLACE TABLE CALENDAR_DIM(
    CAL_DT  DATE NOT NULL,
    CAL_TYPE_NAME   VARCHAR(30),
    DAY_OF_WK_NUM   NUMBER(2,0),
    YR_NUM  NUMBER(4,0),
    WK_NUM  NUMBER(2,0),
    YR_WK_NUM   NUMBER(10,0),
    MNTH_NUM    NUMBER(2,0),
    YR_MNTH_NUM NUMBER(10,0),
    QTR_NUM NUMBER(1,0),
    YR_QTR_NUM  NUMBER(10,0),
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE STORE_DIM(
    STORE_KEY NUMBER(10,0),
    STORE_NUM NUMBER(10,0),
    ADDR    VARCHAR(25),
    CITY  VARCHAR(25),
    REGION VARCHAR(25),
    CNTRY_CD    VARCHAR(5),
    CNTRY_NM    VARCHAR(20),
    POSTAL_ZIP_CD    VARCHAR(15),
    PROV_NAME  VARCHAR(5),
    PROV_CODE  VARCHAR(5),
    MARKET_KEY  NUMBER(3,0),
    MARKET_NAME VARCHAR(25),
    SUBMARKET_KEY   NUMBER(3,0),
    SUBMARKET_NAME  VARCHAR(25),
    LATITUDE    NUMBER(15,6),
    LONGITUDE   NUMBER(15,6),
    TLOG_ACTIVE_FLG	BOOLEAN,
    START_DATE DATE,
    END_DATE DATE,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);


CREATE OR REPLACE TABLE PRODUCT_DIM(
    PROD_KEY NUMBER(38,2),
    PROD_NAME   VARCHAR(150),
    VOL NUMBER(38,2),
    WGT NUMBER(38,2),
    BRAND_NAME  VARCHAR(50),
    STATUS_CODE NUMBER(2,0),
    STATUS_CODE_NAME    VARCHAR(20),
    CATEGORY_KEY    INTEGER,
    CATEGORY_NAME   VARCHAR(50),
    SUBCATEGORY_KEY INTEGER,
    SUBCATEGORY_NAME    VARCHAR(50),
    TLOG_ACTIVE_FLG	boolean,
    START_DATE DATE,
    END_DATE DATE,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE INVENTORY(
    CAL_DT  DATE,
    STORE_KEY   INTEGER,
    PROD_KEY    NUMBER(38,0),
    STOCK_ON_HAND_QTY   NUMBER(38,2),
    ORDERED_STOCK NUMBER(38,2),
    OUT_OF_STOCK_FLG    BOOLEAN,
    WASTE_QTY   NUMBER(38,2),
    PROMOTION_FLG   BOOLEAN,
    NEXT_DELIVERY_DT    DATE,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
--ALTER TABLE WALETP.DAILY_SALES RENAME COLUMN TRANS_DT TO CAL_DT;
CREATE OR REPLACE TABLE DAILY_SALES(
   CAL_DT DATE,
   PROD_KEY	NUMBER(38,2),
   STORE_KEY NUMBER(10,0),
   SALES_QTY NUMBER(38,2),
   SALES_PRICE NUMBER(38,2),
   SALES_AMT NUMBER(38,2),
   DISCOUNT NUMBER(5,2),
   SALES_COST NUMBER(38,2),
   SALES_MARGIN NUMBER(38,2),
   SHIP_COST NUMBER(38,2),
   UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

--ALTER TABLE WALETP.SALES RENAME COLUMN TRANDS_DT TO TRANS_DT;
--ALTER TABLE WALETP.DAILY_SALES RENAME TO WALETP.SALES_DAILY;
--DROP TABLE WALETP.SALES_SALES;