DROP DATABASE IF EXISTS WALMART_DEV;

CREATE DATABASE IF NOT EXISTS WALMART_DEV;
CREATE SCHEMA IF NOT EXISTS WALLND;
CREATE SCHEMA IF NOT EXISTS WALETP;
CREATE SCHEMA IF NOT EXISTS WALSUP;

USE SCHEMA WALMART_DEV.WALLND;

-----------CREATE FILE FORMAT---------------
CREATE OR REPLACE STAGE WALMART_DEV.WALLND.CSV_FORMAT
	TYPE = CSV
	FIELD_DELIMITER = ','
	SKIP_HEADER = 1;

-----------CREATE STAGING AREA---------------
CREATE OR REPLACE STAGE WALMART_DEV.WALLND.FILES_STAGE
	FILE_FORMAT = WALMART_DEV.WALLND.CSV_FORMAT;


-----------CREATE LANDING TABLES------------
CREATE OR REPLACE TABLE WALMART_DEV.WALLND.CALENDAR(
    CAL_DT  DATE,
    CAL_TYPE_DESC   VARCHAR(10),
    DAY_OF_WK_NUM   NUMBER(2,0),
    DAY_OF_WK_DESC  VARCHAR(10),
    YR_NUM  NUMBER(4,0),
    WK_NUM  NUMBER(2,0),
    YR_WK_NUM   NUMBER(10,0),
    MNTH_NUM    NUMBER(2,0),
    YR_MNTH_NUM NUMBER(10,0),
    QTR_NUM NUMBER(1,0),
    YR_QTR_NUM  NUMBER(10,0)
);

CREATE OR REPLACE TABLE WALMART_DEV.WALLND.INVENTORY(
    CAL_DT  DATE,
    STORE_KEY   NUMBER(10,0),
    PROD_KEY    NUMBER(38,0),
    INVENTORY_ON_HAND_QTY   NUMBER(38,2),
    INVENTORY_ON_HAND_ORDER_QTY NUMBER(38,2),
    OUT_OF_STOCK_FLG    NUMBER(2,0),
    WASTE_QTY   NUMBER(38,2),
    PROMOTION_FLG   BOOLEAN,
    NEXT_DELIVERY_DT    DATE
);

CREATE OR REPLACE TABLE WALMART_DEV.WALLND.PRODUCT(
    PROD_KEY NUMBER(38,2),
    PROD_NAME   VARCHAR(50),
    VOL NUMBER(38,2),
    WGT NUMBER(38,2),
    BRAND_NAME  VARCHAR(50),
    STATUS_CODE NUMBER(2,0),
    STATUS_CODE_NAME    VARCHAR(20),
    CATEGORY_KEY    NUMBER(2,0),
    CATEGORY_NAME   VARCHAR(50),
    SUBCATEGORY_KEY NUMBER(2,0),
    SUBCATEGORY_NAME    VARCHAR(50)
);


CREATE OR REPLACE TABLE WALMART_DEV.WALLND.STORE(
    STORE_KEY NUMBER(10,0),
    STORE_NUM NUMBER(10,0),
    STORE_DESC   VARCHAR(20),
    ADDR    VARCHAR(25),
    CITY  VARCHAR(25),
    REGION VARCHAR(25),
    CNTRY_CD    VARCHAR(5),
    CNTRY_NM    VARCHAR(20),
    POSTAL_ZIP_CD    VARCHAR(15),
    PROV_STATE_DESC  VARCHAR(5),
    PROV_STATE_CD  VARCHAR(5),
    STORE_TYPE_CD   VARCHAR(10),
    STORE_TYPE_DESC VARCHAR(20),
    FRNCHS_FLG  VARCHAR(20),
    STORE_SIZE  VARCHAR(20),
    MARKET_KEY  NUMBER(3,0),
    MARKET_NAME VARCHAR(25),
    SUBMARKET_KEY   NUMBER(3,0),
    SUBMARKET_NAME  VARCHAR(25),
    LATITUDE    NUMBER(15,6),
    LONGITUDE   NUMBER(15,6)
);

CREATE OR REPLACE TABLE WALMART_DEV.WALLND.SALES(
   TRANS_ID	NUMBER(20,0),
   PROD_KEY	NUMBER(38,2),
   STORE_KEY NUMBER(10,0),
   TRANS_DT DATE,
   TRANS_TIME NUMBER(5,2),
   SALES_QTY NUMBER(38,2),
   SALES_PRICE NUMBER(38,2),
   SALES_AMT NUMBER(38,2),
   DISCOUNT NUMBER(5,2),
   SALES_COST NUMBER(38,2),
   SALES_MARGIN NUMBER(38,2),
   SHIP_COST NUMBER(38,2)
);

--ALTER TABLE WALLND.SALES RENAME COLUMN TRANDS_DT TO TRANS_DT;